### PR TITLE
[FEATURE-Issue-32] Enhanced HTML Templating Utilities for html/template

### PR DESCRIPTION
**Pull request by mattjinks**
- Enhance Go’s html/template library by incorporating a comprehensive set of utility functions.
- This will enable more expressive and powerful templating, making it easier to handle inline conditionals, loops, and a variety of string, numeric, and date operations within templates.
- Add Documentation for templates package

## Summary by CodeRabbit

- **New Features**
	- Introduced a "Templates" section in the documentation, detailing dynamic rendering capabilities for HTML and text templates.
	- Added functions for rendering HTML and text templates, enhancing the Utils library's functionality.
	- Included a variety of custom utility functions for string manipulation, date formatting, arithmetic operations, and debugging.

- **Bug Fixes**
	- Improved handling of HTML rendering with safe HTML output.

- **Tests**
	- Implemented a comprehensive suite of tests for HTML template rendering to ensure functionality and correctness.

### CODE REVIEW

**Review by kashifkhan0771 — COMMENTED** [review]
I should not be leaving any comments on a draft PR but IMO we should stick to same pattern as text templating.

**Comment by mattjinks** [comment]
> I should not be leaving any comments on a draft PR but IMO we should stick to same pattern as text templating.

Sorry for the confusion, but I thought I was following the same pattern as text templating. Could you clarify the deviation? Also should I be paying attention to the suggestions that coderabbitai makes on my PR, or should I just worry about your feedback?

**Comment by kashifkhan0771** [comment]
> Sorry for the confusion, but I thought I was following the same pattern as text templating. Could you clarify the deviation? Also should I be paying attention to the suggestions that coderabbitai makes on my PR, or should I just worry about your feedback?

The pattern I want to follow is to define custom funcs in custom func file and than add a parse func separately for HTML parsing. About the feedback from Coderabbit, you do not need to worry about that unless it's something too critical. That is for the help of reviewers, If we need something from suggestions, we will merge it as a new commit in the PR.

**Review by kashifkhan0771 — APPROVED** [review]
LGTM! More enhancement can be made in upcoming PR's.
Thank you for the contribution @mattjinks. Keep an eye on issues list and you can pick any which you are interested in. You can also create new feature requests, if you have something on mind.

**Pull request merged**
