### PR TITLE
added advance text templating functions

### PR DESCRIPTION
**Pull request by kashifkhan0771**
## Summary by CodeRabbit

- **New Features**
	- Introduced custom functions for Go templates, including string manipulation, date formatting, arithmetic operations, and debugging tools.
	- Added a `RenderText` function for processing text templates with dynamic data input.

- **Tests**
	- Implemented a comprehensive suite of unit tests for the `RenderText` function, validating various scenarios and functionalities to ensure reliable template rendering.

### CODE REVIEW

**Comment by kashifkhan0771** [comment]
@coderabitai review

**Comment by kashifkhan0771** [comment]
@coderabbitai review

**Comment by kashifkhan0771** [comment]
@coderabbitai review

**Review by shahzadhaider1 — APPROVED** [review]
GW

**Pull request merged**
